"
PseudostateKind is an Enumeration type that is used to differentiate various kinds of Pseudostates.
"
Class {
	#name : 'OPUMLPseudostateKind',
	#superclass : 'OPUMLEnumeration',
	#category : 'OP-UML-Metamodel-StateMachines',
	#package : 'OP-UML-Metamodel',
	#tag : 'StateMachines'
}

{ #category : 'accessing - enum' }
OPUMLPseudostateKind class >> choice [
	^ #choice

]

{ #category : 'accessing - enum' }
OPUMLPseudostateKind class >> deepHistory [
	^ #deepHistory

]

{ #category : 'accessing - enum' }
OPUMLPseudostateKind class >> entryPoint [
	^ #entryPoint

]

{ #category : 'accessing - enum' }
OPUMLPseudostateKind class >> exitPoint [
	^ #exitPoint

]

{ #category : 'accessing - enum' }
OPUMLPseudostateKind class >> fork [
	^ #fork

]

{ #category : 'accessing - enum' }
OPUMLPseudostateKind class >> initial [
	^ #initial

]

{ #category : 'accessing - enum' }
OPUMLPseudostateKind class >> join [
	^ #join

]

{ #category : 'accessing - enum' }
OPUMLPseudostateKind class >> junction [
	^ #junction

]

{ #category : 'accessing - enum' }
OPUMLPseudostateKind class >> shallowHistory [
	^ #shallowHistory

]

{ #category : 'accessing - enum' }
OPUMLPseudostateKind class >> terminate [
	^ #terminate

]

{ #category : 'accessing' }
OPUMLPseudostateKind >> choice [
	^ #choice

]

{ #category : 'accessing' }
OPUMLPseudostateKind >> deepHistory [
	^ #deepHistory

]

{ #category : 'accessing' }
OPUMLPseudostateKind >> entryPoint [
	^ #entryPoint

]

{ #category : 'accessing' }
OPUMLPseudostateKind >> exitPoint [
	^ #exitPoint

]

{ #category : 'accessing' }
OPUMLPseudostateKind >> fork [
	^ #fork

]

{ #category : 'accessing' }
OPUMLPseudostateKind >> initial [
	^ #initial

]

{ #category : 'accessing' }
OPUMLPseudostateKind >> join [
	^ #join

]

{ #category : 'accessing' }
OPUMLPseudostateKind >> junction [
	^ #junction

]

{ #category : 'accessing' }
OPUMLPseudostateKind >> shallowHistory [
	^ #shallowHistory

]

{ #category : 'accessing' }
OPUMLPseudostateKind >> terminate [
	^ #terminate

]
